### PR TITLE
Fix artist image consistency and fallback logic

### PR DESCRIPTION
**Pull request by u7630748**
## Description  
This PR addresses an inconsistency in the artist image display between the search results and the individual artist view. Previously, the artist's picture was visible in the search results but not on the artist's dedicated page. The solution implements a fallback mechanism to reuse the background image when only one image is available.

## Changes Made  
- Implemented a fallback mechanism to ensure the artist image is displayed on the artist's page when only one image is available.
- Updated the rendering logic to check for the availability of multiple images.

## Screenshots  
**Original Search Results (with thumbnail displayed):**  
Original Search Result 1  
Original Search Result 2  

**After Modifications (Search Page):**  
Modified Search Page  

**Artist Page (After Modifications):**  
Artist Page

### CODE REVIEW

**Comment by Evie-YW** [comment]
According to the contribution guidelines provided, contributors are required to run npm test before submitting their changes. This step ensures that all tests pass, maintaining the quality and functionality of the code. Please make sure to follow this process meticulously to comply with the project's standards.

**Comment by Evie-YW** [comment]
According to the contribution guidelines provided, contributors are required to run npm test before submitting their changes. This step ensures that all tests pass, maintaining the quality and functionality of the code. Please make sure to follow this process meticulously to comply with the project's standards.

**Comment by Yi-Wang126** [comment]
According to the contribution guidelines provided, contributors are required to run npm test before submitting their changes. This step ensures that all tests pass, maintaining the quality and functionality of the code. Please make sure to follow this process meticulously to comply with the project's standards.

**Comment by u7630748** [comment]
We should also use prettier for formatting as our code will introduce some whitespace (from maintainer feedback).

**Comment by Siyi-Liu42** [comment]
I have tested the code according to the testing process, and all tests have passed, as shown in the screenshot. Everything should be functioning correctly now.
截屏2024-10-16 13 00 56

**Comment by u7630748** [comment]
The pull request should be good to go now.

**Pull request merged**
